spring:
  application:
    name: employee-demo
  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres1
    url: jdbc:postgresql://postgres:5432/postgres1
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

#logging:
#  level:
#    root: DEBUG
#    org:
#      springframework:
#        kafka: DEBUG
#      confluent:
#        kafka: DEBUG
server:
  port: 8081

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
#      defaultZone: http://localhost:8761/eureka
      defaultZone: http://eureka-server:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      request-headers:
        enabled: true
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      fetchEmployeeR4J:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 15
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 6s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - java.lang.Exception
          - feign.FeignException
          - org.springframework.web.client.RestClientException
        ignoreExceptions:
          - java.lang.IllegalArgumentException
  timelimiter:
    instances:
      fetchEmployeeR4J:
        time-out-duration: 8s

  retry:
    instances:
      fetchEmployeeR4J:
        maxAttempts: 10
        waitDuration: 8s

  ratelimiter:
    instances:
      fetchEmployeeR4J:
        timeoutDuration: 10s
        limitRefreshPeriod: 30s
        limitForPeriod: 3

  bulkhead:
    instances:
      fetchEmployeeR4J:
        max-concurrent-calls: 2
        max-wait-duration: 0