spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: employee-application
          uri: lb://EMPLOYEE-DEMO
          predicates:
            - Path=/employee/v1/**
        - id: notification-module
          uri: lb://NOTIFICATIONMODULE
          predicates:
            - Path=/api/v1/notification/**
        - id: leave-demo-application
          uri: lb://LEAVE-DEMO-APPLICATION
          predicates:
            - Path=/api/v1/leave/**
#        - id: eureka-server
#          uri: http://localhost:8761
#          predicates:
#              - Path=/eureka/**
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #      defaultZone: http://localhost:8761/eureka
      defaultZone: http://eureka-server:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true

server:
  port: 9000